# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20683d702937921732a7346039c463df7f6a6b50012a3c6d04ab123949c5b8b72502251dc6603ef5636f5197351205df74ea818b7bdf97d743293ba0cfba16aa

test:
  secret_key_base: 4693c618f53ed393075f606a6fb035d8cd98e1fcba003eba08979b7dc37e2478ab251cf34749deb41a735fc3de2ca3d3c272824c9583ec4310dc997cb01aeaf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
